### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/awesome-framework#11]
Looking for community-validated RAM that people have successfully used with the Framework so I can add them to the repo. If you've used any, post it in the comments of this issue. Include a link if possible.

**Comment by puff** [comment]
[CT2K16G4SFD832A](https://www.amazon.com/Crucial-3200MHz-2933MHz-2666MHz-CT2K16G4SFD832A/dp/B07Q7T9NSC) is a 32GB, dual ranked CL22, 3200MHz JEDEC kit that works fine on my framework :)
![image](https://user-images.githubusercontent.com/33184334/203615726-a73d326d-0e4e-42e2-8b58-2115c9d6caf0.png)

**Comment by fhteagle** [comment]
SK Hynix HMAA1GS6CJR6N 8GB, 3200MTs, CL22

SK Hynix HMA41GS6AFR8N 8GB, 2133MTs, CL19 I think

SK Hynix HMA851S6DJR6N 4GB, 3200MTs, CL22

**Comment by Morpheus636** [comment]
Just a heads up, all three community validated hardware requests will be added tonight or tomorrow and these RFC issues will be closed. If anyone has others to add, please do so now.

Once they're closed, please open a new issue for anything additional you'd like to see added.

**Comment by Morpheus636** [comment]
> SK Hynix HMA41GS6AFR8N 8GB, 2133MTs, CL19 I think

I'm gonna leave this one out as it goes against Framework's recommendation of 3200 native speeds. Thanks for contributing!
