### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/awesome-framework#12]
Looking for some community-validated SSDs that people have successfully used with the Framework so I can add them to the repo. If you've used any, post it in the comments of this issue. Include a link if possible.

**Comment by puff** [comment]
[SK Hynix Gold P31 1TB](https://www.amazon.com/SK-hynix-Gold-PCIe-Internal/dp/B08DKB5LWY) is a drive recommended by many in the framework community because of its low power draw and fast PCIe 3.0 speeds.

**Comment by lamdv** [comment]
[Crucial P1 500GB](https://www.amazon.de/-/en/Crucial-CT500P1SSD8-500GB-Internal-NAND/dp/B07J2WBKXF?th=1) for me because I am cheap and it's fast enough

**Comment by fhteagle** [comment]
SK Hynix P31 500GB and an older SK Hynix  BC501A 128GB SSD (2230 plus 3d printed length adapter) also works very well for me.

**Comment by Morpheus636** [comment]
> (2230 plus 3d printed length adapter)

I plan to include the SK Hyinx P31 500GB, but I'm going to exclude anything that doesn't fit out of the box. 

I'm trying to avoid anything that is an unsupported length, as taping it (which is not what you recommended, but people will try it) can damage the M.2 connector.

**Comment by BelArvardan** [comment]
[WD_BLACK 1TB SN850](https://www.amazon.com/gp/product/B08KFS6THF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) NVMe has worked great.

I added this [heatsink](https://www.amazon.com/gp/product/B07YC1HTFR/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)  which is thin enough for the framework.

**Comment by Morpheus636** [comment]
Just a heads up, all three community validated hardware requests will be added tonight or tomorrow and these RFC issues will be closed. If anyone has others to add, please do so now.

Once they're closed, please open a new issue for anything additional you'd like to see added.

**Comment by Morpheus636** [comment]
> [Crucial P1 500GB](https://www.amazon.de/-/en/Crucial-CT500P1SSD8-500GB-Internal-NAND/dp/B07J2WBKXF?th=1) for me because I am cheap and it's fast enough

I'm not including this because I'm having trouble finding an equivalent link on US amazon (which is where I'm trying to make all the links to for consistency sake). If you find a link to it, please open a new issue. Thanks!

**Comment by Morpheus636** [comment]
> [WD_BLACK 1TB SN850](https://www.amazon.com/gp/product/B08KFS6THF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) NVMe has worked great.

It's on the officially validated list! Thanks for the input though!
