### ISSUE TITLE
Linux Battery Life Improvements - Basics

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/awesome-framework#17]
Add a battery life sub-page to the linux directory for outlining tips to improve battery to replace the forum thread, which is disorganized, unsearchable, and completely wrong in some places. It should include the following:

- [ ] Basics
  - [ ] Hardware
    - [ ] Expansion Card Selection
    - [ ] SSD Selection
  - [ ] Powertop (For monitoring ONLY)
  - [ ] TLP (For power management)
    - [ ] Disabling Turbo
  - [ ] Hardware Acceleration

An advanced section will be opened at a later date, and an RFC will be opened to gather information about it.

**Comment by fhteagle** [comment]
SSD selection for low idle wattage, fast drop to deep idle, good MB written per watt, etc. SK Hynix P31 is great for this.

TLP configuration for aspme to superpowersave was the only basic tuning I did.

Turning down brightness is the biggest wattage saving strategy out of them all.

**Comment by Morpheus636** [comment]
Gonna go ahead and close this now since Matt is working on an official guide.
