### ISSUE TITLE
Charging Accessories

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/awesome-framework#22]
Please share any chargers and other charging accessories that you've tested and used with your Framework here!

**Comment by lamdv** [comment]
I have used this Ugreen 65W GaN charger as main charger for a while and it works flawlessly for me: https://www.amazon.de/Charger-Adapter-Supports-Compatible-MacBook-black/dp/B091BRJSRN

Anker 45W NanoII also work in a pinch, but more slowly and might drain under heavy load

Lenovo 65W charger carried over from an old ThinkPad also worked well, although bigger.

Dell 27" display USB C port charges without problem and without draining. I will update the model name once I back in office
